### ISSUE TITLE
consider using git submodules and allowing local builds of bamliquidator?

### ISSUE THREAD

**Issue by semenko** [BradnerLab/pipeline#45]
I am working on a cluster where I don't always have bits / it's tedious to install global library packages.

Perhaps we can consider including samtools/htslib, etc. as git submodules, then building them for the bamliquidator module in the makefile

**Comment by jdimatteo** [comment]
Hi, I'm not a big fan of git submodules.  See this: https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/

Is your cluster Ubuntu?  Maybe we could try writing a script to do one of the solutions here?  http://askubuntu.com/questions/339/how-can-i-install-a-package-without-root-access

**Comment by semenko** [comment]
That's one option -- I've personally worked around this a few ways (static linking with an older libc & moving the binary, just extracting the .deb, passing extra flags for libs, etc.).

I just find it's a bit of a hassle for normal users -- and is a headache whenever I suggest to someone to install bamliquidator (and they lack root bits, etc.)

**Comment by jdimatteo** [comment]
Have you tried collecting all the .so libraries on a machine you have root access to install normally with apt-get, then transferring them over to the machine you don't have access to and setting LD_LIBRARY_PATH?  How do you deal with missing python libraries like pytables?

What operating system and version is a typical use case?  E.g. Ubuntu 14.04?  If you provide me an OS version and share what you've tried so far (particularly about python libraries), maybe I can test and get something working.  Any help would be appreciated, as I'm trying to focus on writing new motif finding code.

**Comment by jdimatteo** [comment]
Closing this as there has been no response for a few months.  Please re-open if this is important to you and you can share some details of a typical use case.

**Comment by semenko** [comment]
Oh cool -- no worries. I did some hackish module things -- works fine :+1:
