### ISSUE TITLE
bamliquidator crashes after failed absurdly large memory allocation

### ISSUE THREAD

**Issue by jdimatteo** [BradnerLab/pipeline#46]
With a specific bam, bamliquidator crashes with a bin size of 30,000 but works fine for a bin size of 40,000.

````
jdm@tod:~/Gunk/tmp_large_alloc$ bamliquidator_batch -b 30000 test.bam                                    Liquidating test.bam (file 1 of 1)
tcmalloc: large alloc 18446744071562067968 bytes == (nil) @
Liquidation completed: 0.583112 seconds, 24334613 reads, 41.158474 millions of reads per second
Traceback (most recent call last):
  File "/usr/bin/bamliquidator_batch", line 9, in <module>
    load_entry_point('BamLiquidatorBatch==1.2.0', 'console_scripts', 'bamliquidator_batch')()
  File "/usr/lib/python2.7/dist-packages/bamliquidatorbatch/bamliquidator_batch.py", line 503, in main
    not args.quiet, args.number_of_threads, args.black_list)
  File "/usr/lib/python2.7/dist-packages/bamliquidatorbatch/bamliquidator_batch.py", line 256, in __init__   
    self.batch(extension, sense)
  File "/usr/lib/python2.7/dist-packages/bamliquidatorbatch/bamliquidator_batch.py", line 205, in batch
    raise Exception("%s failed with exit code %d" % (self.executable_path, return_code))
Exception: bamliquidator_bins failed with exit code -11
jdm@tod:~/Gunk/tmp_large_alloc$ rm -rf output/
jdm@tod:~/Gunk/tmp_large_alloc$ bamliquidator_batch -b 40000 test.bam
Liquidating test.bam (file 1 of 1)
tcmalloc: large alloc 1073741824 bytes == 0x2ff82000 @
Liquidation completed: 5.087825 seconds, 24334613 reads, 4.717143 millions of reads per second
Cell Types: -
Normalizing and calculating percentiles for cell type -
Indexing normalized counts
Plotting
-- skipping plotting chrM because not enough bins (only 1)
-- skipping plotting chrM because not enough bins (only 1)
Summarizing
Post liquidation processing took 7.320600 seconds
jdm@tod:~/Gunk/tmp_large_alloc$ 
````

**Comment by jdimatteo** [comment]
I confirmed that this crash for smaller bins doesn't occur for other bams.  There seems to be something special about this bam.

**Comment by jdimatteo** [comment]
I tracked this down to some internals of samtools while reading the region chr1:30000-60000.  In function bam_read1 in bam.c, bam_read/bgzf_read is called to populate a block_len variable.  The value is calculated to be about 1.4 billion, which is not a valid value.  When the call to kroundup32 rounds it up to 2.8 billion it overflows (since it is a 32 bit signed integer), then it is passed as an unsigned 64 bit size argument to realloc, which is interpreted as the absurdly large number 18446744071562067968.  This of course fails, and returns a nullptr but samtools doesn't check for the error nullptr case.  The block_len calculation of 1.4 billion in bgzf_read seems to be some strange result of reading 4 bytes at a time in a samtools structure.

If you run samtools view for this region a similar crash occurs:

`
jdm@tod:~/Gunk/tmp_large_alloc$ samtools view test.bam chr1:30000-60000
Segmentation fault (core dumped)
`

We are using samtools version 0.1.19-96b5f2294a from March 2013.

If we run this same command on a more recent samtools version 1.2-56-g5e6d7bd we get a helpful error message:

`samtools view ~/gunk/del_me/test.bam chr1:30000-60000
[main_samview] retrieval of region "chr1:30000-60000" failed due to truncated file or corrupt BAM index file
`

We might want to consider upgrading to the latest stable version of samtools, which would likely better handle this bam file.  But I'm going to go ahead and close this defect since the input is bad and there is nothing straightforward to do to better handle this bad input.

**Comment by bradnerComputation** [comment]
Thanks John!

-Charles

Charles Y. Lin, Ph.D.
Dana-Farber Cancer Institute
Department of Medical Oncology
charles_lin@dfci.harvard.edu<mailto:charles_lin@dfci.harvard.edu>
http://bradnerlab.com
