### ISSUE TITLE
procedure to add a reference genome

### ISSUE THREAD

**Issue by mpallocc** [BradnerLab/pipeline#56]
Dear all,

I'd really like to thank you for this amazing tool combo. 

I was trying to use the rose pipeline script but unfortunately I found out that there is no support for hg38 genome.

I wanted to double check with you a possible workaround to add the genome myself, other than adding the option in the python script, I think I need to add a couple of files in the annotation/ folder:

- hg38.chrom.sizes
- hg19_refseq.ucsc (this is just the GTF file from UCSC hgTable's tool with gene annotation ,right? any particular filters-parameters I need to know of?)
- ucsc_chromSize.txt (should i just append hg38.chrom.sizes to this file?)

Am I missing something else?

thank you very much!
Matteo

**Comment by jdimatteo** [comment]
@mpallocc I'm very sorry, I must have missed this question.  Are you still trying to get an alternate reference genome set up?  If so, I'll reopen this issue, but I'm closing for now because I assume I am far too late to be helpful at this point.

**Comment by mpallocc** [comment]
Dear John,

yes, Indeed at the end I managed to add the reference genome, I actually can't remember exactly how but for sure I added those files and maybe just changed a couple of lines in the main ROSE pipeline code every time there were human genome references.

**Comment by mpallocc** [comment]
[brad.zip](https://github.com/BradnerLab/pipeline/files/1386869/brad.zip)

**Comment by mpallocc** [comment]
thanks again for the tool. I hope to show you some published results in a few months :)
