### ISSUE TITLE
Error in bamToGFF.py

### ISSUE THREAD

**Issue by gunjangala** [BradnerLab/pipeline#58]
Hi,
I am trying to use ```bamToGFF.py``` but when run it I get the following error:
```
mapping to GFF and making a matrix with fixed bin number
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
bamToGFF.py in <module>()
    424
    425 if __name__ == "__main__":
--> 426     main()

bamToGFF.py in main()
    407         elif options.matrix:
    408             print('mapping to GFF and making a matrix with fixed bin number')
--> 409             newGFF = mapBamToGFF(bamFile,gffFile,options.sense,options.unique,int(options.extension),options.floor,options.density,options.rpm,25,None,options.matrix,False,options.jxn)
    410
    411         else:

bamToGFF.py in mapBamToGFF(bamFile, gff, sense, unique, extension, floor, density, rpm, binSize, clusterGram, matrix, raw, includeJxnReads)
    110         unique = False
    111         if rpm:
--> 112             MMR= round(float(bam.getTotalReads('mapped'))/1000000,4)
    113         else:
    114             MMR = 1

TypeError: float() argument must be a string or a number
```

Command used:
```
module unload python
module load python/2.7
python bamToGFF.py -b ${BAM_FILE} -i ${GFF_FILE} -o ${OUTPUT} -e 400 -m 25 -r 
```

Files to reproduce this error can be found [here](https://drive.google.com/file/d/0BwKNPkK6si-BOFRwWWJlSXZnUEU/view?usp=sharing)

Can you please help me fix this error?

Thanks,
Gunjan

**Comment by charlesylin** [comment]
Hi Gunjan,

That error is usually caused when the initial bam is unsorted. If your bam
is sorted and indexed, I'll take a look at your example files when I get a
chance


Charles Y. Lin
Assistant Professor
Department of Molecular and Human Genetics
Dan L. Duncan Cancer Center
Baylor College of Medicine

**Comment by gunjangala** [comment]
Yes, the BAM files used are sorted and indexed.

**Comment by charlesylin** [comment]
is path to samtools "samtools" on your machine? what is your OS?

Charles Y. Lin
Assistant Professor
Department of Molecular and Human Genetics
Dan L. Duncan Cancer Center
Baylor College of Medicine

**Comment by gunjangala** [comment]
Yes, the path is "samtools". I am using SGE cluster (unix/linux environments).

**Comment by gunjangala** [comment]
The error got fixed. It works fine giving the desired output now.

**Comment by chlchan** [comment]
@gunjangala Can you explain what the error was and how it was fixed?

**Comment by gunjangala** [comment]
The error was because of incorrect path of python module.
