### ISSUE TITLE
real examples with data and output

### ISSUE THREAD

**Issue by GodloveD** [BradnerLab/pipeline#71]
I am an administrator installing bamliquidator on behalf of a user.  So I don't have enough background information to test the installation once it's completed.  It would be great if you could provide some sample data and some sample commands in the readme that will produce expected output.  That way and admin like myself can install this software and test it without knowing a lot about omics etc.  Thanks for considering this request!

**Comment by jdimatteo** [comment]
GodloveD, you can test with the files linked from here: https://github.com/BradnerLab/pipeline/wiki/bamliquidator#performance

E.g.

wget https://www.dropbox.com/s/a71ngagu2k8pgiv/04032013_D1L57ACXX_4.TTAGGC.hg18.bwt.sorted.bam
wget https://www.dropbox.com/s/a71ngagu2k8pgiv/04032013_D1L57ACXX_4.TTAGGC.hg18.bwt.sorted.bam.bai
bamliquidator_batch --flatten 04032013_D1L57ACXX_4.TTAGGC.hg18.bwt.sorted.bam 

I will upload the expected results this evening.

Depending on how you installed, you can also run the unit tests, e.g. `python bamliquidatorbatch/test.py` -- https://github.com/BradnerLab/pipeline/blob/master/bamliquidator_internal/bamliquidatorbatch/test.py

**Comment by jdimatteo** [comment]
Sorry for the delay. I’ll follow up tonight.

**Comment by jdimatteo** [comment]
Please run the following (and please note that one of the wget links in the prior message was wrong, so please don't skip any of these commands):

```
wget https://www.dropbox.com/s/bu75ojqr2ibkf57/04032013_D1L57ACXX_4.TTAGGC.hg18.bwt.sorted.bam
wget https://www.dropbox.com/s/a71ngagu2k8pgiv/04032013_D1L57ACXX_4.TTAGGC.hg18.bwt.sorted.bam.bai
wget https://www.dropbox.com/s/g7rcde76jya11y0/04032013_D1L57ACXX_4.TTAGGC.hg18.summary_chr1.tab
bamliquidator_batch --flatten 04032013_D1L57ACXX_4.TTAGGC.hg18.bwt.sorted.bam
```

Then you can compare the actual output with the expected output; diff should report that the downloaded file and the locally calculated file are identical:

```
diff -qs 04032013_D1L57ACXX_4.TTAGGC.hg18.summary_chr1.tab output/summary_chr1.tab
Files 04032013_D1L57ACXX_4.TTAGGC.hg18.summary_chr1.tab and output/summary_chr1.tab are identical
```

Please let me know if this resolves your immediate concern for testing your particular install.

Let's leave this issue open until the documentation is improved so the next person can reasonably test without opening a github issue.

**Comment by GodloveD** [comment]
Thanks so much for providing these links and instructions.  I'll take a look when I can and let you know if it works for me.  😄

**Comment by GodloveD** [comment]
This procedure works great.  I guess the main weakness is whether or not the dropbox links will remain current, but as long as they are not broken, this is a good procedure.  I captured this in a script and submitted PR #72 to make it even easier.  This should make documenting on the wiki a breeze.

**Comment by jdimatteo** [comment]
I'll keep the dropbox links working as long as I'm alive, hopefully that is good enough lol
